---
title: "Lista 5"
author: "Fabiano Carvalho Vasques Junior"
format: typst
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "me315.sqlite")


```

1\. Qual seria a nova área (em acres) de cada reserva natural caso sua área atual fosse aumentada em 20%? Apresente o nome da reserva, a área atual e a nova área após o aumento.

```{sql connection = con}
SELECT PNAME, ACRES,
       ACRES * 120/100 AS area_nova
FROM PRESERVE;
```

2\. Qual seria a área de cada reserva natural se sua área atual fosse reduzida para um terço do tamanho atual?
Apresente o nome da reserva, a área atual em acres e a área ajustada em acres.

```{sql connection = con}
SELECT PNAME, ACRES, 
        ACRES * 1/3 AS area_ajustada
        FROM PRESERVE;
```

3\. Para todas as reservas naturais, apresente o nome da reserva e sua taxa de entrada atual. Apresente também uma taxa ajustada, calculada adicionando US\$ 50,00 à taxa atual, em seguida, dividindo o resultado por 2.

```{sql connection = con}
SELECT PNAME, FEE,
        (FEE + 50)/2.0 AS NEW_FEE
        FROM PRESERVE;

```

4. Apresente os valores médio, máximo e mínimo de ACRES para todas as reservas naturais localizadas no Arizona.
```{sql connection = con}
SELECT AVG(ACRES) AS AVG_ACRES,
       MAX(ACRES) AS MAX_ACRES,
       MIN(ACRES) AS MIN_ACRES
FROM PRESERVE;
WHERE STATE = 'AZ';

```

5. Apresente o primeiro nome de reserva em ordem alfabética.

```{sql connection = con}
SELECT PNAME
FROM PRESERVE
ORDER BY PNAME ASC
LIMIT 1;

```

6. Desconsidere as taxas de entrada iguais a zero. Quantas taxas de entrada distintas existem na tabela PRESERVE?

```{sql connection = con}
SELECT COUNT(DISTINCT FEE)
FROM PRESERVE
WHERE FEE != 0;
```
7. Escreva uma instrução SELECT que demonstre que PNAME não contém atualmente valores duplicados.

```{sql connection = con}
SELECT PNAME, COUNT(*) AS QTD
FROM PRESERVE
GROUP BY PNAME
HAVING COUNT(*) > 1;
```
8. Suponha que você pretenda estabelecer uma nova política para o cálculo das taxas de entrada. Cada reserva natural cobrará uma taxa de US$ 0,02 por acre. Qual será a taxa média de entrada das reservas naturais localizadas no Arizona?
```{sql connection = con}
SELECT  AVG(ACRES * 0.02) AS NEW_FEE
FROM PRESERVE
WHERE STATE = 'AZ';

```
9. Suponha que o salário de cada funcionário seja aumentado em 10%. Apresente o número do funcionário, seu nome, salário antigo e novo salário. A tabela resultante deve ter quatro colunas denominadas ENO, ENAME, OLDSALARY e NEWSALARY. Ordene o resultado pelo novo salário.
```{sql connection = con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY * 1.1 AS NEWSALARY
FROM EMPLOYEE
ORDER BY NEWSALARY DESC;

```

10. Modifique o exercício anterior. Apresente apenas os registros dos funcionários cujo novo salário seja superior a US$ 2.000,00.
```{sql connection = con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY * 1.1 AS NEWSALARY
FROM EMPLOYEE
WHERE NEWSALARY > 2000
ORDER BY NEWSALARY DESC;
```
11.Apresente a soma, a média, o valor máximo e o valor mínimo de todos os valores de SALARY.
```{sql connection = con}
SELECT AVG(SALARY),
       MAX(SALARY),
       MIN(SALARY)
FROM EMPLOYEE       

```
12. Quantos funcionários trabalham no Departamento 20?
```{sql connection = con}
SELECT COUNT(*) as QEM
FROM EMPLOYEE 
WHERE DNO = 20;
```
13 Quantos departamentos possuem funcionários?
```{sql connection = con}
SELECT COUNT(DISTINCT DNO) AS QDEP
FROM EMPLOYEE;
```

